### ISSUE TITLE
There‘s something wrong with Fintuned with Vicuna 13B

### ISSUE THREAD

**Issue by Kevin-GJ** [opendatalab/VIGC#18]
There‘s something wrong with Fintuned with Vicuna 13B，as follows:
 size mismatch for llm_proj.weight: copying a param with shape torch.Size([5120, 768]) from checkpoint, the shape in current model is torch.Size([4096, 768]).
        size mismatch for llm_proj.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).

**Comment by HanxSmile** [comment]
It looks like that you are loading a vicuna13B pretrain weight into a vicuna7B model. Could you provide the yaml file you are training with? Maybe it's because the `model_type` field and `pretrained` or `finetuned` field are mismatch.
