### ISSUE TITLE
How to inference on my custom dataset?

### ISSUE THREAD

**Issue by Keep-lucky** [opendatalab/VIGC#3]
Excuse me， I want to use VIGC to inference on my custom dataset, what modifications should I make?

**Comment by HanxSmile** [comment]
You may need to modify the content of `vigc/configs/datasets/coco_pseudo/vig_test.yaml`，in which `annotation` should be changed to the path to the json file containing all image names, and `images` should be changed to the directory path of images.

The content of the `annotation` json file should be:
```json
[
  {
    "image": "train2017/000000082363.jpg",
    "question": "",
    "image_id": 82363
  },
  {
    "image": "train2017/000000060126.jpg",
    "question": "",
    "image_id": 60126
  },
 ...
]
```

Then you can use the config file `vigc/projects/mini_gpt4_vicuna7b/generate_qa/llava-150k/generate_llava_qa_complex.yaml`, `vigc/projects/mini_gpt4_vicuna7b/generate_qa/llava-150k/generate_llava_qa_conv.yaml` or `vigc/projects/mini_gpt4_vicuna7b/generate_qa/llava-150k/generate_llava_qa_detail.yaml` to inference on your dataset.
