### ISSUE TITLE
which weights in "pretrained"?

### ISSUE THREAD

**Issue by shipengai** [opendatalab/VIGC#8]
In file mini_gpt4_vicuna7b.yaml,
which weights is the "pretrained"?

**Comment by wufan-tb** [comment]
you can follow our instruction to get them.
![image](https://github.com/opendatalab/VIGC/assets/34300920/eec507c5-20c3-4a8b-b0e0-bee611dd2e26)

**Comment by shipengai** [comment]
> you can follow our instruction to get them. ![image](https://user-images.githubusercontent.com/34300920/269204251-eec507c5-20c3-4a8b-b0e0-bee611dd2e26.png)

hahaha, which weights is the "finetuned"?

**Comment by wufan-tb** [comment]
the third part of `Prepare Models`
![image](https://github.com/opendatalab/VIGC/assets/34300920/4791d417-692f-4477-b64b-72ebf8f5d49d)
