### ISSUE TITLE
NO file vigc_demo.sh

### ISSUE THREAD

**Issue by shipengai** [opendatalab/VIGC#9]

**Comment by HanxSmile** [comment]
Hi, we've update README.md to explain how to run the demo locally:

To Launch a demo locally, you should:

1. Download the pretrain weight and finetune weight of minigpt-4 and instructblip to local;

2. Update `MODEL_CKPT` in line 9 of `vigc_demo.py`；

3. Run `python vigc_demo.py` and then follow the instruction on the prompts to view in browser. Arguments are as follows:

* `--device0`: The gpu id of the first model

* `--device1`: The gpu id of the second model
